weights: yolov5n.pt
cfg: ''
data: pingpong_yolov5/pingpong.yaml
hyp:
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 0.05
  cls: 0.5
  cls_pw: 1.0
  obj: 1.0
  obj_pw: 1.0
  iou_t: 0.2
  anchor_t: 4.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.0
  copy_paste: 0.0
epochs: 50
batch_size: 8
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
evolve_population: yolov5/data/hyps
resume_evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: true
single_cls: false
optimizer: Adam
sync_bn: false
workers: 8
project: pingpong_training
name: pingpong_detection
exist_ok: true
quad: false
cos_lr: true
label_smoothing: 0.1
patience: 10
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: 1
artifact_alias: latest
ndjson_console: false
ndjson_file: false
save_dir: pingpong_training/pingpong_detection
